import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import "react-datepicker/dist/react-datepicker.css";

const Open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "openTable",
  description: "Generated by create khalil naoueji",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Open.className} bg-gray-100 min-h-screen w-screen`}>
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
